### ISSUE TITLE
Add blacklist support

### ISSUE THREAD

**Issue by attilaolah** [wercker/step-golint#4]
It would be nice to be able to exclude files from being linted. Preferably a regexp, something like this:

```yml
build:
  steps:
    - golint:
        exclude: "\.pb\.go"
```

Probably something like `grep -ve $EXCLUDE_PATTERN` would do.

See https://github.com/golang/lint/issues/98 why this would be interesting.
